title: Artist Bushel In Elephants
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Ryan Schuster
  email: bob@bobjoe.com

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: neuroblog/all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"


exclude: ['sitemap.xml','feed.xml', 'LICENSE', 'README.md']
